# server:
#   ports:
#       - "8761:8761"
# eureka:
#   client:
#     registerWithEureka: false
#     fetchRegistry: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/